### ISSUE TITLE
Bots don't buy any items

### ISSUE THREAD

**Issue by sterlp** [adamqqqplay/dota2ai#135]
With the new 7.34b, which seems to have some more issues, the bots don't buy items anymore. Same applies also to the default bots.

**Comment by adamqqqplay** [comment]
@sterlp I think we have fixed this issue, please try to update your mod.

**Comment by sterlp** [comment]
@adamqqqplay today it is fixed for the default bots and **dota2ai**; where was an update of DOTA, so I assume it was a general issue for both bots.

**Comment by adamqqqplay** [comment]
> @adamqqqplay today I tested it again. It work if I play alone with bots, it stop working as soon I play together with one more human player; both use random, but I assume the last part doesn't make any difference.
> 
> Same issue with the default bot, works fine alone, with two players they also stop working.

@sterlp Can you try it on the local server? Maybe a recent update caused a bug in Valve's official server.

**Comment by kiddailey** [comment]
Still see this all the time.  In a game with default bots today one bot opponent didn't buy anything.  The other 4 opponent bots purchased starting items, but then not another thing for the rest of the game.

**Comment by sterlp** [comment]
Hello @adamqqqplay,

I am currently not playing any Dota anymore but as @kiddailey  mentioned it seems still to be open. I have to reinstall it to verify it. Sorry dude.

Happy new year

Paul
